[package]
name = "facet-diff"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Diffing capabilities for types implementing the Facet trait"
keywords = ["facet", "diff", "comparison", "reflection", "data-structures"]
categories = ["development-tools", "data-structures"]

[dependencies]
facet = { version = "0.27.13", path = "../facet" }
facet-core = { version = "0.27.13", path = "../facet-core" }
facet-pretty = { version = "0.23.23", path = "../facet-pretty" }
facet-reflect = { version = "0.27.13", path = "../facet-reflect" }
