[package]
name = "facet"
version = "0.1.4"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Re-exports the Facet trait and derive macros, along with Shape and all related types"
keywords = ["facet", "introspection", "reflection"]
categories = ["development-tools"]

[dependencies]
facet-trait.workspace = true
facet-derive.workspace = true

[features]
# Does nothing, only used for tests
testfeat = []
std = ["facet-trait/std"]
default = ["std"]

[dev-dependencies]
facet-spez = { path = "../facet-spez" }
