[package]
name = "shapely-samplelibc"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[build-dependencies]
cc = "1.2.18"

[dependencies]
shapely = { version = "3.1.1", path = "../shapely" }
