name: Binary Size Analysis

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  bloat-check:
    runs-on: depot-ubuntu-24.04-16

    container:
      image: ghcr.io/facet-rs/facet-ci:latest-amd64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ✨ Configure git safe directory
        shell: bash
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: Swatinem/rust-cache@v2

      - name: ✨ Install cargo-bloat and cargo-llvm-lines
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-bloat,cargo-llvm-lines

      - name: ✨ Build and analyze PR branch
        shell: bash
        run: |
          cargo bloat --release --manifest-path outside-workspace/bigapi-cli-facet/Cargo.toml -n 30 | .github/scripts/process-bloat-output.sh > pr-bloat.txt
          cargo bloat --release --manifest-path outside-workspace/bigapi-cli-facet/Cargo.toml --crates -n 30 | .github/scripts/process-bloat-output.sh > pr-bloat-crates.txt

          # LLVM lines analysis
          cargo llvm-lines --release --manifest-path outside-workspace/bigapi-types-facet/Cargo.toml | head -30 | .github/scripts/process-llvm-lines.sh > pr-llvm-lines-types.txt
          cargo llvm-lines --release --manifest-path outside-workspace/bigapi-indirection-facet/Cargo.toml | head -30 | .github/scripts/process-llvm-lines.sh > pr-llvm-lines-indirection.txt

      - name: ✨ Checkout main branch
        shell: bash
        run: |
          # Stash any changes (like Cargo.lock files) before switching branches
          git stash --include-untracked
          git checkout main
          # Re-apply the changes (path dependencies) after switching
          git stash pop || true

      - name: ✨ Build and analyze main branch
        shell: bash
        run: |
          cargo bloat --release --manifest-path outside-workspace/bigapi-cli-facet/Cargo.toml -n 30 | .github/scripts/process-bloat-output.sh > main-bloat.txt
          cargo bloat --release --manifest-path outside-workspace/bigapi-cli-facet/Cargo.toml --crates -n 30 | .github/scripts/process-bloat-output.sh > main-bloat-crates.txt

          # LLVM lines analysis
          cargo llvm-lines --release --manifest-path outside-workspace/bigapi-types-facet/Cargo.toml | head -30 | .github/scripts/process-llvm-lines.sh > main-llvm-lines-types.txt
          cargo llvm-lines --release --manifest-path outside-workspace/bigapi-indirection-facet/Cargo.toml | head -30 | .github/scripts/process-llvm-lines.sh > main-llvm-lines-indirection.txt

      - name: ✨ Generate comparison
        shell: bash
        run: |
          echo "## 📊 Binary Size Analysis" > bloat-report.md
          echo "" >> bloat-report.md
          echo "Comparison of binary sizes between \`main\` and this PR:" >> bloat-report.md
          echo "" >> bloat-report.md

          # Extract total size from both files (from the last line)
          MAIN_SIZE=$(grep "\.text section size" main-bloat.txt | awk '{print $3}')
          PR_SIZE=$(grep "\.text section size" pr-bloat.txt | awk '{print $3}')

          # Calculate the difference
          # Extract numeric value and unit separately
          MAIN_VALUE=$(echo $MAIN_SIZE | sed 's/[^0-9.]//g')
          MAIN_UNIT=$(echo $MAIN_SIZE | sed 's/[0-9.]//g')
          PR_VALUE=$(echo $PR_SIZE | sed 's/[^0-9.]//g')
          PR_UNIT=$(echo $PR_SIZE | sed 's/[0-9.]//g')

          # Convert to bytes using awk for floating point math
          if [[ $MAIN_UNIT == "MiB" ]]; then
            MAIN_BYTES=$(awk "BEGIN {printf \"%.0f\", $MAIN_VALUE * 1048576}")
          elif [[ $MAIN_UNIT == "KiB" ]]; then
            MAIN_BYTES=$(awk "BEGIN {printf \"%.0f\", $MAIN_VALUE * 1024}")
          else
            MAIN_BYTES=$MAIN_VALUE
          fi

          if [[ $PR_UNIT == "MiB" ]]; then
            PR_BYTES=$(awk "BEGIN {printf \"%.0f\", $PR_VALUE * 1048576}")
          elif [[ $PR_UNIT == "KiB" ]]; then
            PR_BYTES=$(awk "BEGIN {printf \"%.0f\", $PR_VALUE * 1024}")
          else
            PR_BYTES=$PR_VALUE
          fi

          DIFF_BYTES=$((PR_BYTES - MAIN_BYTES))
          if [ $DIFF_BYTES -gt 0 ]; then
            DIFF_SIGN="+"
            DIFF_EMOJI="📈"
          elif [ $DIFF_BYTES -lt 0 ]; then
            DIFF_SIGN=""
            DIFF_EMOJI="📉"
          else
            DIFF_SIGN=""
            DIFF_EMOJI="✅"
          fi

          # Format the difference
          if [ $DIFF_BYTES -ne 0 ]; then
            ABS_DIFF=${DIFF_BYTES#-}
            if [ $ABS_DIFF -gt 1048576 ]; then
              DIFF_FMT="${DIFF_SIGN}$(awk "BEGIN {printf \"%.2f\", $DIFF_BYTES / 1048576}") MiB"
            elif [ $ABS_DIFF -gt 1024 ]; then
              DIFF_FMT="${DIFF_SIGN}$(awk "BEGIN {printf \"%.2f\", $DIFF_BYTES / 1024}") KiB"
            else
              DIFF_FMT="${DIFF_SIGN}${DIFF_BYTES} B"
            fi
          else
            DIFF_FMT="No change"
          fi

          echo "| Branch | Total Size | Difference |" >> bloat-report.md
          echo "|--------|------------|------------|" >> bloat-report.md
          echo "| main   | $MAIN_SIZE | - |" >> bloat-report.md
          echo "| **PR** | **$PR_SIZE** | **${DIFF_EMOJI} ${DIFF_FMT}** |" >> bloat-report.md
          echo "" >> bloat-report.md
          
          # Extract LLVM line counts (from the TOTAL line)
          MAIN_LINES_TYPES=$(grep "(TOTAL)" main-llvm-lines-types.txt | awk '{print $1}')
          PR_LINES_TYPES=$(grep "(TOTAL)" pr-llvm-lines-types.txt | awk '{print $1}')
          MAIN_LINES_INDIRECTION=$(grep "(TOTAL)" main-llvm-lines-indirection.txt | awk '{print $1}')
          PR_LINES_INDIRECTION=$(grep "(TOTAL)" pr-llvm-lines-indirection.txt | awk '{print $1}')
          
          # Calculate differences
          DIFF_LINES_TYPES=$((PR_LINES_TYPES - MAIN_LINES_TYPES))
          DIFF_LINES_INDIRECTION=$((PR_LINES_INDIRECTION - MAIN_LINES_INDIRECTION))
          
          # Format line count differences
          if [ $DIFF_LINES_TYPES -gt 0 ]; then
            DIFF_LINES_TYPES_FMT="+$DIFF_LINES_TYPES"
            DIFF_LINES_TYPES_EMOJI="📈"
          elif [ $DIFF_LINES_TYPES -lt 0 ]; then
            DIFF_LINES_TYPES_FMT="$DIFF_LINES_TYPES"
            DIFF_LINES_TYPES_EMOJI="📉"
          else
            DIFF_LINES_TYPES_FMT="No change"
            DIFF_LINES_TYPES_EMOJI="✅"
          fi
          
          if [ $DIFF_LINES_INDIRECTION -gt 0 ]; then
            DIFF_LINES_INDIRECTION_FMT="+$DIFF_LINES_INDIRECTION"
            DIFF_LINES_INDIRECTION_EMOJI="📈"
          elif [ $DIFF_LINES_INDIRECTION -lt 0 ]; then
            DIFF_LINES_INDIRECTION_FMT="$DIFF_LINES_INDIRECTION"
            DIFF_LINES_INDIRECTION_EMOJI="📉"
          else
            DIFF_LINES_INDIRECTION_FMT="No change"
            DIFF_LINES_INDIRECTION_EMOJI="✅"
          fi
          
          echo "### LLVM Line Counts" >> bloat-report.md
          echo "" >> bloat-report.md
          echo "| Crate | Main | PR | Difference |" >> bloat-report.md
          echo "|-------|------|----|-----------:|" >> bloat-report.md
          echo "| bigapi-types-facet | $MAIN_LINES_TYPES | $PR_LINES_TYPES | ${DIFF_LINES_TYPES_EMOJI} ${DIFF_LINES_TYPES_FMT} |" >> bloat-report.md
          echo "| bigapi-indirection-facet | $MAIN_LINES_INDIRECTION | $PR_LINES_INDIRECTION | ${DIFF_LINES_INDIRECTION_EMOJI} ${DIFF_LINES_INDIRECTION_FMT} |" >> bloat-report.md
          echo "" >> bloat-report.md

          # Generate diff
          echo "### Diff (by function)" >> bloat-report.md
          echo '```diff' >> bloat-report.md
          diff -u main-bloat.txt pr-bloat.txt >> bloat-report.md || true
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md

          echo "### Diff (by crate)" >> bloat-report.md
          echo '```diff' >> bloat-report.md
          diff -u main-bloat-crates.txt pr-bloat-crates.txt >> bloat-report.md || true
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md

          echo "### LLVM Lines (bigapi-types-facet)" >> bloat-report.md
          echo '```diff' >> bloat-report.md
          diff -u main-llvm-lines-types.txt pr-llvm-lines-types.txt >> bloat-report.md || true
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md

          echo "### LLVM Lines (bigapi-indirection-facet)" >> bloat-report.md
          echo '```diff' >> bloat-report.md
          diff -u main-llvm-lines-indirection.txt pr-llvm-lines-indirection.txt >> bloat-report.md || true
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md

          echo "<details>" >> bloat-report.md
          echo "<summary>Full outputs</summary>" >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### Main branch (by function)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat main-bloat.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### PR branch (by function)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat pr-bloat.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### Main branch (by crate)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat main-bloat-crates.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### PR branch (by crate)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat pr-bloat-crates.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### Main branch LLVM Lines (bigapi-types-facet)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat main-llvm-lines-types.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### PR branch LLVM Lines (bigapi-types-facet)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat pr-llvm-lines-types.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### Main branch LLVM Lines (bigapi-indirection-facet)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat main-llvm-lines-indirection.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### PR branch LLVM Lines (bigapi-indirection-facet)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat pr-llvm-lines-indirection.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "</details>" >> bloat-report.md

      - name: ✨ Save PR info
        run: |
          echo "${{ github.event.pull_request.number }}" > pr-number.txt

      - name: ✨ Upload analysis report
        uses: actions/upload-artifact@v4
        with:
          name: bloat-analysis-report
          path: |
            bloat-report.md
            pr-number.txt
          retention-days: 7
